/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Original Tasks
         * @description Read the source Excel workbook fresh and return task rows as-originally-defined.
         *     Independent of any Randomise / Modify / Products edits that have hit the DB.
         */
        get: operations["list_original_tasks_tasks_original_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_tasks__task_id__patch"];
        trace?: never;
    };
    "/schedule/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Run */
        post: operations["trigger_run_schedule_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        /**
         * Delete All Runs
         * @description Wipe every ScheduleRun + ScheduledAssignment. Task master data is left intact.
         *     After this, the next run's id is 1 (SQLite reuses rowids when the table is empty).
         */
        delete: operations["delete_all_runs_runs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Metrics */
        get: operations["get_run_metrics_runs__run_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricsRead */
        MetricsRead: {
            /** Machine Utilization */
            machine_utilization: {
                [key: string]: number;
            };
            /** Component Waiting Days */
            component_waiting_days: {
                [key: string]: number;
            };
            /** Product Waiting Days */
            product_waiting_days: {
                [key: string]: number;
            };
            /** Late Counts */
            late_counts: {
                [key: string]: number;
            };
        };
        /** ScheduleRunCreate */
        ScheduleRunCreate: {
            /** Notes */
            notes?: string | null;
        };
        /** ScheduleRunDetail */
        ScheduleRunDetail: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
            /** Notes */
            notes?: string | null;
            /** Assignments */
            assignments: components["schemas"]["ScheduledAssignmentRead"][];
        };
        /** ScheduleRunRead */
        ScheduleRunRead: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
            /** Notes */
            notes?: string | null;
        };
        /** ScheduledAssignmentRead */
        ScheduledAssignmentRead: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: number;
            /** Task Id */
            task_id: number;
            /** Split Index */
            split_index: number;
            /** Assigned Quantity */
            assigned_quantity: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Unique Id */
            unique_id: number;
            /** Sr No */
            sr_no?: number | null;
            /** Product Name */
            product_name: string;
            /**
             * Order Processing Date
             * Format: date-time
             */
            order_processing_date: string;
            /**
             * Promised Delivery Date
             * Format: date-time
             */
            promised_delivery_date: string;
            /** Quantity Required */
            quantity_required: number;
            /** Component */
            component: string;
            /** Operation */
            operation?: string | null;
            /** Process Type */
            process_type?: string | null;
            /** Machine Number */
            machine_number: string;
            /** Run Time Per 1000 */
            run_time_per_1000: number;
            /** Cycle Time Seconds */
            cycle_time_seconds?: number | null;
            /** Setup Time Seconds */
            setup_time_seconds?: number | null;
            /**
             * Status
             * @default InProgress
             */
            status: string;
        };
        /** TaskRead */
        TaskRead: {
            /** Unique Id */
            unique_id: number;
            /** Sr No */
            sr_no?: number | null;
            /** Product Name */
            product_name: string;
            /**
             * Order Processing Date
             * Format: date-time
             */
            order_processing_date: string;
            /**
             * Promised Delivery Date
             * Format: date-time
             */
            promised_delivery_date: string;
            /** Quantity Required */
            quantity_required: number;
            /** Component */
            component: string;
            /** Operation */
            operation?: string | null;
            /** Process Type */
            process_type?: string | null;
            /** Machine Number */
            machine_number: string;
            /** Run Time Per 1000 */
            run_time_per_1000: number;
            /** Cycle Time Seconds */
            cycle_time_seconds?: number | null;
            /** Setup Time Seconds */
            setup_time_seconds?: number | null;
            /**
             * Status
             * @default InProgress
             */
            status: string;
            /** Id */
            id: number;
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Unique Id */
            unique_id?: number | null;
            /** Sr No */
            sr_no?: number | null;
            /** Product Name */
            product_name?: string | null;
            /** Order Processing Date */
            order_processing_date?: string | null;
            /** Promised Delivery Date */
            promised_delivery_date?: string | null;
            /** Quantity Required */
            quantity_required?: number | null;
            /** Component */
            component?: string | null;
            /** Operation */
            operation?: string | null;
            /** Process Type */
            process_type?: string | null;
            /** Machine Number */
            machine_number?: string | null;
            /** Run Time Per 1000 */
            run_time_per_1000?: number | null;
            /** Cycle Time Seconds */
            cycle_time_seconds?: number | null;
            /** Setup Time Seconds */
            setup_time_seconds?: number | null;
            /** Status */
            status?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_original_tasks_tasks_original_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
        };
    };
    get_task_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_schedule_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScheduleRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRunRead"][];
                };
            };
        };
    };
    delete_all_runs_runs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_metrics_runs__run_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
